apiVersion: v1
data:
  rabbitmq-password: RlFpQlhZbW5ZWlBxWXV2Mg==
kind: Secret
metadata:
  creationTimestamp: "2022-08-23T11:36:10Z"
  labels:
    app.kubernetes.io/instance: testkavyakr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
  name: testkavyakr-rabbitmq
  namespace: default
type: Opaque