apiVersion: v1
data:
  rabbitmq-password: YndlajZuNWZsekxGRGE1VA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: testkavyam1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-10.3.0
  name: testkavyam1-rabbitmq
  namespace: default
type: Opaque